[build]
  command = "yarn docs:content && yarn docs:build"
  publish = "dist"
  [build.environment]
    NODE_VERSION="12"
    NODE_ENV = "production"
    YARN_FLAGS="--production=false"
  [build.processing]
    skip_processing = true

[context.production.environment]
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
